import { storageTypeImage } from "./mediaPaths";
import type { NearbyFacility } from "../types/storiq";

/** Starter sample data — replace via Master Data import before client demos. */
export const sampleFacilities: NearbyFacility[] = [
  {
    id: "mgs-belton-i35",
    facilityName: "My Garage Self Storage | I-35",
    city: "Belton",
    state: "TX",
    address: "1234 I-35 Frontage Rd, Belton, TX 76513",
    zipCode: "76513",
    storagelyUrl: "https://www.mygarageselfstorage.com/self-storage/tx/belton/i-35/",
    imageUrl: storageTypeImage("climate_controlled_storage.png"),
    notes: "Sample data — import real facilities CSV",
  },
  {
    id: "mgs-temple-loop",
    facilityName: "My Garage Self Storage | Loop 363",
    city: "Temple",
    state: "TX",
    address: "4501 Loop 363, Temple, TX 76502",
    zipCode: "76502",
    storagelyUrl: "https://www.mygarageselfstorage.com/self-storage/tx/temple/loop-363/",
    imageUrl: storageTypeImage("business_storage.png"),
  },
  {
    id: "mgs-killeen-central",
    facilityName: "My Garage Self Storage | Central Killeen",
    city: "Killeen",
    state: "TX",
    address: "2500 E Central Texas Expy, Killeen, TX 76543",
    zipCode: "76543",
    storagelyUrl: "https://www.mygarageselfstorage.com/self-storage/tx/killeen/central/",
    imageUrl: storageTypeImage("vehicle_storage.png"),
  },
  {
    id: "mgs-salado-main",
    facilityName: "My Garage Self Storage | Main Street",
    city: "Salado",
    state: "TX",
    address: "901 N Main St, Salado, TX 76571",
    zipCode: "76571",
    storagelyUrl: "https://www.mygarageselfstorage.com/self-storage/tx/salado/main-street/",
    imageUrl: storageTypeImage("indoor_storage.png"),
  },
  {
    id: "mgs-georgetown-north",
    facilityName: "My Garage Self Storage | North Georgetown",
    city: "Georgetown",
    state: "TX",
    address: "7800 Williams Dr, Georgetown, TX 78633",
    zipCode: "78633",
    storagelyUrl: "https://www.mygarageselfstorage.com/self-storage/tx/georgetown/north/",
    imageUrl: storageTypeImage("rv_storage.png"),
  },
  {
    id: "mgs-waco-south",
    facilityName: "My Garage Self Storage | South Waco",
    city: "Waco",
    state: "TX",
    address: "7100 Bagby Ave, Waco, TX 76712",
    zipCode: "76712",
    storagelyUrl: "https://www.mygarageselfstorage.com/self-storage/tx/waco/south/",
    imageUrl: storageTypeImage("truck_storage.png"),
  },
];
