import type { NearbyFacility } from "../types/storiq";

/** Starter sample data — replace via Master Data import before client demos. */
export const sampleFacilities: NearbyFacility[] = [
  {
    id: "mgs-belton-i35",
    facilityName: "My Garage Self Storage | I-35",
    city: "Belton",
    state: "TX",
    address: "1234 I-35 Frontage Rd, Belton, TX 76513",
    zipCode: "76513",
    storagelyUrl: "https://www.mygarageselfstorage.com/self-storage/tx/belton/i-35/",
    imageUrl: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=600&q=80",
    notes: "Sample data — import real facilities CSV",
  },
  {
    id: "mgs-temple-loop",
    facilityName: "My Garage Self Storage | Loop 363",
    city: "Temple",
    state: "TX",
    address: "4501 Loop 363, Temple, TX 76502",
    zipCode: "76502",
    storagelyUrl: "https://www.mygarageselfstorage.com/self-storage/tx/temple/loop-363/",
    imageUrl: "https://images.unsplash.com/photo-1553413077-190dd305871c?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "mgs-killeen-central",
    facilityName: "My Garage Self Storage | Central Killeen",
    city: "Killeen",
    state: "TX",
    address: "2500 E Central Texas Expy, Killeen, TX 76543",
    zipCode: "76543",
    storagelyUrl: "https://www.mygarageselfstorage.com/self-storage/tx/killeen/central/",
    imageUrl: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "mgs-salado-main",
    facilityName: "My Garage Self Storage | Main Street",
    city: "Salado",
    state: "TX",
    address: "901 N Main St, Salado, TX 76571",
    zipCode: "76571",
    storagelyUrl: "https://www.mygarageselfstorage.com/self-storage/tx/salado/main-street/",
    imageUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "mgs-georgetown-north",
    facilityName: "My Garage Self Storage | North Georgetown",
    city: "Georgetown",
    state: "TX",
    address: "7800 Williams Dr, Georgetown, TX 78633",
    zipCode: "78633",
    storagelyUrl: "https://www.mygarageselfstorage.com/self-storage/tx/georgetown/north/",
    imageUrl: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "mgs-waco-south",
    facilityName: "My Garage Self Storage | South Waco",
    city: "Waco",
    state: "TX",
    address: "7100 Bagby Ave, Waco, TX 76712",
    zipCode: "76712",
    storagelyUrl: "https://www.mygarageselfstorage.com/self-storage/tx/waco/south/",
    imageUrl: "https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?auto=format&fit=crop&w=600&q=80",
  },
];
