import { nearbyLocationImage } from "./mediaPaths";
import type { NearbyFacility } from "../types/storiq";

/** Starter sample data — images from `public/media-library/nearby-locations/`. */
export const sampleFacilities: NearbyFacility[] = [
  {
    id: "mgs-belton-i35",
    facilityName: "My Garage Self Storage | I-35",
    city: "Belton",
    state: "TX",
    address: "1234 I-35 Frontage Rd, Belton, TX 76513",
    zipCode: "76513",
    storagelyUrl: "https://www.mygarageselfstorage.com/self-storage/tx/belton/i-35/",
    imageUrl: nearbyLocationImage("self-storage-units-in-belton.jpg"),
    notes: "Sample data — import real facilities CSV",
  },
  {
    id: "mgs-temple-loop",
    facilityName: "My Garage Self Storage | Loop 363",
    city: "Temple",
    state: "TX",
    address: "4501 Loop 363, Temple, TX 76502",
    zipCode: "76502",
    storagelyUrl: "https://www.mygarageselfstorage.com/self-storage/tx/temple/loop-363/",
    imageUrl: nearbyLocationImage("self-storage-units-in-temple-south-31.webp"),
  },
  {
    id: "mgs-killeen-central",
    facilityName: "My Garage Self Storage | Central Killeen",
    city: "Killeen",
    state: "TX",
    address: "2500 E Central Texas Expy, Killeen, TX 76543",
    zipCode: "76543",
    storagelyUrl: "https://www.mygarageselfstorage.com/self-storage/tx/killeen/central/",
    imageUrl: nearbyLocationImage("self-storage-units-in-killeen.webp"),
  },
  {
    id: "mgs-morgans-point-resort",
    facilityName: "My Garage Self Storage | Morgan's Point Resort",
    city: "Morgan's Point Resort",
    state: "TX",
    address: "120 Lakeshore Dr, Morgan's Point Resort, TX 76513",
    zipCode: "76513",
    storagelyUrl: "https://www.mygarageselfstorage.com/self-storage/tx/morgans-point-resort/",
    imageUrl: nearbyLocationImage("self-storage-units-in-morgans-point-resort.webp"),
  },
  {
    id: "mgs-copperas-cove",
    facilityName: "My Garage Self Storage | Copperas Cove",
    city: "Copperas Cove",
    state: "TX",
    address: "1201 US-190, Copperas Cove, TX 76522",
    zipCode: "76522",
    storagelyUrl: "https://www.mygarageselfstorage.com/self-storage/tx/copperas-cove/",
    imageUrl: nearbyLocationImage("self-storage-units-in-copperas-cove.webp"),
  },
  {
    id: "mgs-tyler",
    facilityName: "My Garage Self Storage | Tyler",
    city: "Tyler",
    state: "TX",
    address: "4500 Troup Hwy, Tyler, TX 75703",
    zipCode: "75703",
    storagelyUrl: "https://www.mygarageselfstorage.com/self-storage/tx/tyler/",
    imageUrl: nearbyLocationImage("self-storage-units-in-tyler.webp"),
  },
];
